version: '3.9'

services:
  influxdb:
    image: influxdb:2.7 # You can specify a different InfluxDB 2.x version if needed
    container_name: influxdb_ct
    restart: unless-stopped
    ports:
      - "8086:8086" # Default InfluxDB port
    volumes:
      - influxdb_data:/var/lib/influxdb2 # Persists InfluxDB data
      - influxdb_config:/etc/influxdb2  # Persists InfluxDB configuration
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup # Initialize a new instance
      - DOCKER_INFLUXDB_INIT_USERNAME=myadminuser # Change this
      - DOCKER_INFLUXDB_INIT_PASSWORD=mysecretadminpassword # Change this
      - DOCKER_INFLUXDB_INIT_ORG=my-org # Change this or use default
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket # Change this or use default
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myverysecretadmintoken # Change this securely
      # - DOCKER_INFLUXDB_INIT_RETENTION= # Optional: e.g., 1w for 1 week, 0 for infinite
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:10.4.2 # Using a specific recent version of Grafana
    container_name: grafana_ct
    restart: unless-stopped
    ports:
      - "3000:3000" # Default Grafana web UI port
    volumes:
      - grafana_data:/var/lib/grafana # Persists Grafana dashboards, plugins, etc.
      # You can also mount a custom grafana.ini if needed:
      # - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      # GF_SECURITY_ADMIN_USER: admin # Default is admin
      # GF_SECURITY_ADMIN_PASSWORD: admin # Default is admin, CHANGE THIS on first login
      # GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource # Example plugins
      GF_DEFAULT_INSTANCE_NAME: MyGrafanaInstance
    depends_on:
      - influxdb # Ensures InfluxDB starts before Grafana attempts to connect
    networks:
      - monitor-net

volumes:
  influxdb_data: # Named volume for InfluxDB data
    driver: local
  influxdb_config: # Named volume for InfluxDB config
    driver: local
  grafana_data: # Named volume for Grafana data
    driver: local

networks:
  monitor-net: # Custom network for services to communicate
    driver: bridge
